---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "onramp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "onramp.fullname" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "onramp.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8080 }}
      targetPort: http